export const legalRooms = [
  {
    name: "Laundry",
    roomType: { laundry: {} },
    description: "Clean your dirty clothes.",
    price: 100,
    yield: 10,
    capacity: 100,
    image: "/rooms/laundry.gif",
    levelRequirement: 0,
  },
  {
    name: "Fastfood",
    roomType: { fastFoodRestaurant: {} },
    description: "Serve delicious fast food.",
    price: 600,
    yield: 25,
    capacity: 200,
    image: "/rooms/fastFoodRestaurant.gif",
    levelRequirement: 100,
  },
  {
    name: "Fitness Center",
    roomType: { fitnessCenter: {} },
    description: "Keep fit and healthy.",
    price: 800,
    yield: 35,
    capacity: 300,
    image: "/rooms/fitnessCenter.png",
    levelRequirement: 200,
  },
];

export const illegalRooms = [
  {
    name: "Unlicensed Bar",
    roomType: { unlicensedBar: {} },
    description: "Run an unlicensed bar.",
    price: 400,
    yield: 15,
    capacity: 600,
    image: "/rooms/unlicensedBar.gif",
    levelRequirement: 0,
  },
  {
    name: "Cannabis Farm",
    roomType: { cannabisFarm: {} },
    description: "Grow cannabis.",
    price: 500,
    yield: 20,
    capacity: 400,
    image: "/rooms/cannabisFarm.gif",
    levelRequirement: 1,
  },
  {
    name: "Strip Club",
    roomType: { stripClub: {} },
    description: "Run a strip club.",
    price: 1500,
    yield: 50,
    capacity: 900,
    image: "/rooms/stripClub.png",
    levelRequirement: 6,
  },
  {
    name: "Casino",
    roomType: { casino: {} },
    description: "Run a casino.",
    price: 2000,
    yield: 60,
    capacity: 500,
    image: "/rooms/casino.gif",
    levelRequirement: 2,
  },
  {
    name: "Saferoom",
    roomType: { saferoom: {} },
    description: "Hide your illegal earnings.",
    price: 800,
    yield: 0,
    capacity: 700,
    image: "/rooms/saferoom.png",
    levelRequirement: 4,
  },
  {
    name: "Security Room",
    roomType: { securityRoom: {} },
    description: "Hire enforcers and hitmen.",
    price: 600,
    yield: 0,
    capacity: 800,
    image: "/rooms/securityRoom.gif",
    levelRequirement: 5,
  },
];

export const allRooms = [...legalRooms, ...illegalRooms];
